# 认证服务 - 开发环境主配置文件
# 注意：业务配置和敏感信息已移至Nacos配置中心

# 服务器配置
server:
  port: 8081
  servlet:
    context-path: /auth

# Spring基础配置
spring:
  # 应用名称
  application:
    name: service-auth
  
  # 配置导入 - 从Nacos加载配置
  config:
    import: nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
  
  # Spring Security 默认用户配置（开发环境）
  security:
    user:
      name: ${SECURITY_USER_NAME:admin}
      password: ${SECURITY_USER_PASSWORD:admin123}
      roles: ${SECURITY_USER_ROLES:ADMIN}

  # Nacos服务注册与发现配置
  cloud:
    nacos:
      # 服务发现配置
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:117.50.197.170:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:olN2y)]VzEISLITO#_}L0J^$>Nk)1S~W}
        namespace: ${NACOS_NAMESPACE:ba1493dc-20fa-413b-84e1-d929c9a4aeac}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        # 注册配置
        register-enabled: true
        # 心跳间隔
        heart-beat-interval: 5000
        # 心跳超时时间
        heart-beat-timeout: 15000
        # 实例删除超时时间
        ip-delete-timeout: 30000
      
      # 配置中心配置
      config:
        server-addr: ${NACOS_SERVER_ADDR:117.50.197.170:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:olN2y)]VzEISLITO#_}L0J^$>Nk)1S~W}
        namespace: ${NACOS_NAMESPACE:ba1493dc-20fa-413b-84e1-d929c9a4aeac}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        file-extension: yaml
        # 配置刷新
        refresh-enabled: true
        # 配置超时时间
        timeout: 3000
        # 配置重试次数
        retry-time: 2000
        # 长轮询超时时间
        long-poll-timeout: 46000

  # 启动性能优化（开发环境）
  main:
    lazy-initialization: true  # 开发环境启用懒加载
  # JMX配置
  jmx:
    enabled: false  # 开发环境关闭JMX

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  # 应用信息配置
  info:
    env:
      enabled: true
    git:
      mode: full

# 日志配置（开发环境详细日志）
logging:
  level:
    com.origin.auth: debug
    org.springframework.security: debug
    org.springframework.web: debug
    com.origin.auth.util: debug
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/service-auth.log
    max-size: 100MB
    max-history: 30 