# Service-User Nacos配置模板
# 文件名: service-user-${spring.profiles.active}.yml
# 说明: service-user服务的动态配置模板

# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:banyu_mall}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  # Redis配置
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:1}
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

  # MyBatis-Plus配置
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
      call-setters-on-nulls: true
      jdbc-type-for-null: 'null'
    global-config:
      db-config:
        id-type: assign_id
        logic-delete-field: isDeleted
        logic-delete-value: 1
        logic-not-delete-value: 0
    mapper-locations: classpath*:mapper/**/*.xml

# 服务配置
server:
  port: ${SERVER_PORT:8082}
  servlet:
    context-path: /user

# 应用配置
application:
  name: service-user

# 用户服务特定配置
user:
  # 用户信息缓存配置
  cache:
    enabled: true
    ttl: 3600  # 缓存时间（秒）
  
  # 用户头像配置
  avatar:
    upload-path: /uploads/avatars
    max-size: 5242880  # 5MB
    allowed-types: jpg,jpeg,png,gif
  
  # 用户验证配置
  verification:
    email-verification: false
    phone-verification: false
    real-name-verification: false

# Feign配置
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000
        logger-level: basic
  compression:
    request:
      enabled: true
    response:
      enabled: true

# 自定义Feign配置
user:
  feign:
    auth:
      service-name: service-auth
      timeout: 5000
      retry-count: 3

# 日志配置
logging:
  level:
    com.origin.user: debug
    com.origin.common: info
    org.springframework.cloud.openfeign: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Nacos配置
spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        metadata:
          version: ${APP_VERSION:1.0.0}
          zone: ${APP_ZONE:default}
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        file-extension: yml
        refresh-enabled: true
        shared-configs:
          - data-id: common-config.yml
            group: ${NACOS_GROUP:DEFAULT_GROUP}
            refresh: true

# 性能配置
spring:
  main:
    banner-mode: off
  jmx:
    enabled: false
  cloud:
    discovery:
      enabled: true
    loadbalancer:
      ribbon:
        enabled: false 