# 用户服务 - 生产环境配置（连接Nacos）
spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:localhost:8848}
        namespace: ${NACOS_NAMESPACE:prod}
      config:
        server-addr: ${NACOS_SERVER:localhost:8848}
        namespace: ${NACOS_NAMESPACE:prod}
        file-extension: yml

  # 数据源配置（从Nacos获取）
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://mysql-service:3306/banyu_mall?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000

  data:
    redis:
      host: ${REDIS_HOST:redis-service}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 1
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: -1ms
          max-idle: 10
          min-idle: 5

  # MyBatis-Plus配置
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    global-config:
      db-config:
        logic-delete-field: isDeleted
        logic-delete-value: 1
        logic-not-delete-value: 0
        id-type: assign_id

# 日志配置
logging:
  level:
    com.origin.user: info
    org.springframework: warn
  file:
    name: logs/service-user.log
    max-size: 100MB
    max-history: 30

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# 用户服务生产环境特定配置
user:
  # 生产环境安全配置
  security:
    allow-delete: false
    allow-batch-operations: true
    max-config-count: 50
  # 性能配置
  performance:
          cache-enabled: true
          cache-ttl: 3600
  # 监控配置
  monitoring:
    enabled: true
    metrics-enabled: true 