# 网关服务 - 生产环境主配置文件
# 注意：业务配置和敏感信息已移至Nacos配置中心

# 服务器配置
server:
  port: 8080
  # 移除servlet配置，使用WebFlux配置
  # servlet:
  #   context-path: /gateway

# Spring基础配置
spring:
  # 应用名称
  application:
    name: service-gateway
  
  # 配置导入 - 从Nacos加载配置
  config:
    import: nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
  
  # 明确指定为响应式Web应用
  main:
    web-application-type: reactive
  
  # 自动配置排除 - 避免WebMvc与WebFlux冲突
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.transaction.TransactionAutoConfiguration
  
  # Redis配置 - 用于限流器（响应式）
  # data:
  #   redis:
  #     host: localhost
  #     port: 6379
  #     database: 0
  #     timeout: 3000ms
  #     lettuce:
  #       pool:
  #         max-active: 8
  #         max-idle: 8
  #         min-idle: 0
  #         max-wait: -1ms
  #     # 响应式Redis配置
  #     reactive:
  #       timeout: 3000ms
  
  # Nacos服务注册与发现配置
  cloud:
    nacos:
      # 服务发现配置
      discovery:
        server-addr: 117.50.197.170:8848
        username: nacos
        password: olN2y)]VzEISLITO#_}L0J^$>Nk)1S~W
        namespace: ba1493dc-20fa-413b-84e1-d929c9a4aeac
        group: DEFAULT_GROUP
        # 注册配置
        register-enabled: true
        # 心跳间隔
        heart-beat-interval: 5000
        # 心跳超时时间
        heart-beat-timeout: 15000
        # 实例删除超时时间
        ip-delete-timeout: 30000
      
      # 配置中心配置
      config:
        server-addr: 117.50.197.170:8848
        username: nacos
        password: olN2y)]VzEISLITO#_}L0J^$>Nk)1S~W
        namespace: ba1493dc-20fa-413b-84e1-d929c9a4aeac
        group: DEFAULT_GROUP
        file-extension: yaml
        # 配置刷新
        refresh-enabled: true
        # 配置超时时间
        timeout: 3000
        # 配置重试次数
        retry-time: 2000
        # 长轮询超时时间
        long-poll-timeout: 46000

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: when-authorized
  # 应用信息配置
  info:
    env:
      enabled: true
    git:
      mode: full

# 日志配置（生产环境）
logging:
  config: classpath:log4j2.xml
  level:
    com.origin.gateway: info
    org.springframework.cloud.gateway: info
    org.springframework.web: warn
    # 禁用Log4j2包扫描警告
    org.apache.logging.log4j.status: ERROR
    org.apache.logging.log4j.core.config: ERROR
    root: warn
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/infra-gateway.log
    max-size: 100MB
    max-history: 30

# 网关配置
gateway:
  # 路由配置
  routes:
    - id: auth-service
      uri: lb://service-auth
      predicates:
        - Path=/auth/**
      filters:
        - StripPrefix=0
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 50
            redis-rate-limiter.burstCapacity: 100
    
    - id: user-service
      uri: lb://service-user
      predicates:
        - Path=/user/**
      filters:
        - StripPrefix=0
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 50
            redis-rate-limiter.burstCapacity: 100

  # 全局过滤器配置
  globalcors:
    cors-configurations:
      '[/**]':
        allowedOrigins: "${ALLOWED_ORIGINS:*}"
        allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
        allowedHeaders: "*"
        allowCredentials: true

# 性能优化配置
server:
  # 连接超时时间
  connection-timeout: 20000
  # 读取超时时间
  read-timeout: 30000
  # 写入超时时间
  write-timeout: 30000
  # 最大连接数
  max-connections: 16384
  # 最大线程数
  threads:
    max: 400
    min: 50 