# Nacos配置模板 - infra-gateway.yml
# 将此配置内容复制到Nacos控制台中

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # 认证服务路由
        - id: auth-service
          uri: lb://service-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        # 默认路由 - 转发到认证服务
        - id: default-route
          uri: lb://service-auth
          predicates:
            - Path=/**
          filters:
            - StripPrefix=0

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always

# 网关特定配置
gateway:
  # 跨域配置
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    allow-credentials: true
  
  # 限流配置
  rate-limit:
    enabled: true
    default-rate: 1000  # 默认限流：每秒1000个请求
  
  # 熔断配置
  circuit-breaker:
    enabled: true
    fallback-uri: forward:/fallback
  
  # 路由配置
  routes:
    auth-service:
      path: /auth/**
      strip-prefix: 1
      rate-limit: 500  # 认证服务限流：每秒500个请求
    
    default-route:
      path: /**
      strip-prefix: 0
      rate-limit: 1000  # 默认限流：每秒1000个请求

# 日志配置
logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.origin.gateway: DEBUG
    reactor.netty: WARN 