# 认证服务 - Nacos云端配置
# 文件名: service-auth.yaml
# 命名空间: public
# 分组: DEFAULT_GROUP

# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://mysql-service:3306/banyu_mall?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8}
    username: ${MYSQL_USERNAME:banyu_user}
    password: ${MYSQL_PASSWORD:banyu_password}
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  # Redis配置
  data:
    redis:
      host: ${REDIS_HOST:redis-service}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis_password}
      database: ${REDIS_DATABASE:0}
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: -1ms
          max-idle: 10
          min-idle: 5

  # MyBatis-Plus配置
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true
      call-setters-on-nulls: false
      jdbc-type-for-null: 'null'
      log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    global-config:
      db-config:
        id-type: assign_id
        logic-delete-field: isDeleted
        logic-delete-value: 1
        logic-not-delete-value: 0
    mapper-locations: classpath*:/mapper/**/*.xml
    type-aliases-package: com.origin.auth.entity

  # JWT令牌缓存配置（认证服务必需）
  cache:
    type: redis
    redis:
      time-to-live: 3600000  # 1小时，与JWT过期时间一致
      cache-null-values: false
      key-prefix: "auth:jwt:"

  # 启动性能优化
  main:
    lazy-initialization: false
  jmx:
    enabled: false

# JWT配置
jwt:
  # JWT密钥 - 必须通过环境变量设置
  secret: ${JWT_SECRET}
  # 过期时间（毫秒）- 1小时
  expiration: ${JWT_EXPIRATION:3600000}
  # 令牌前缀
  token-prefix: ${JWT_TOKEN_PREFIX:Bearer}
  # 刷新令牌过期时间（毫秒）- 24小时
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:86400000}
  # 是否启用黑名单
  enable-blacklist: ${JWT_ENABLE_BLACKLIST:true}
  # Redis黑名单前缀
  blacklist-prefix: ${JWT_BLACKLIST_PREFIX:token:blacklist:}
  # Redis有效令牌前缀
  valid-token-prefix: ${JWT_VALID_TOKEN_PREFIX:token:valid:}

# 安全配置
security:
  # 不需要认证的路径
  permit-all:
    - /auth/login
    - /auth/register
    - /auth/refresh
    - /actuator/health
    - /actuator/info
    - /actuator/metrics

# 登录配置
login:
  max-attempts: 3  # 最大登录尝试次数
  lock-duration: 600  # 锁定时间（秒）
  captcha-enabled: true  # 启用验证码
  # 验证码配置
  captcha:
    width: 120
    height: 40
    length: 4
    expire-seconds: 300

# 令牌配置
token:
  refresh-threshold: 300  # 刷新阈值（秒）
  blacklist-cleanup-interval: 3600  # 黑名单清理间隔（秒）
  # 令牌轮换配置
  rotation:
    enabled: true
    threshold: 600  # 剩余时间小于10分钟时轮换

# 线程池配置
thread:
  pool:
    core-size: 20
    max-size: 50
    queue-capacity: 1000
    keep-alive-seconds: 60
    # 线程池监控
    monitor:
      enabled: true
      interval: 60  # 监控间隔（秒）

# 性能优化配置
server:
  # 连接超时时间
  connection-timeout: 20000
  # 读取超时时间
  read-timeout: 30000
  # 写入超时时间
  write-timeout: 30000
  # 最大连接数
  max-connections: 8192
  # 最大线程数
  threads:
    max: 200
    min: 10

# 日志配置
logging:
  level:
    com.origin.auth: warn
    org.springframework.security: warn
    org.springframework.web: warn
    root: warn
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/service-auth.log
    max-size: 100MB
    max-history: 30

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  # 应用信息配置
  info:
    env:
      enabled: true
    git:
      mode: full

# 监控配置
monitoring:
  # 健康检查配置
  health:
    check-interval: 30  # 健康检查间隔（秒）
    timeout: 5000  # 健康检查超时时间（毫秒）
  
  # 指标配置
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: 60s

# 限流配置
rate-limit:
  enabled: true
  # 登录接口限流
  login:
    max-requests: 10  # 最大请求数
    time-window: 60  # 时间窗口（秒）
  # 通用接口限流
  general:
    max-requests: 100  # 最大请求数
    time-window: 60  # 时间窗口（秒）

# 审计日志配置
audit:
  enabled: true
  # 审计事件
  events:
    - LOGIN_SUCCESS
    - LOGIN_FAILURE
    - LOGOUT
    - PASSWORD_CHANGE
    - ACCOUNT_LOCK
  # 审计日志存储
  storage:
    type: database  # database, file, elasticsearch
    table: sys_audit_log 