apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${SERVICE_NAME}
    environment: ${ENVIRONMENT}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "${PORT:-8080}"
    prometheus.io/path: "/actuator/prometheus"
spec:
  selector:
    app: ${SERVICE_NAME}
  ports:
  - name: http
    port: ${PORT:-8080}
    targetPort: http
    protocol: TCP
  type: ClusterIP 