server:
  port: 8080

spring:
  application:
    name: infra-gateway
  
  # 配置导入 - 从Nacos加载配置
  config:
    import: nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
  
  cloud:
    nacos:
      discovery:
        server-addr: 117.50.197.170:8848
        username: nacos
        password: olN2y)]VzEISLITO#_}L0J^$>Nk)1S~W
        namespace: ba1493dc-20fa-413b-84e1-d929c9a4aeac
        group: DEFAULT_GROUP
        # 注册配置
        register-enabled: true
        # 心跳间隔
        heart-beat-interval: 5000
        # 心跳超时时间
        heart-beat-timeout: 15000
        # 实例删除超时时间
        ip-delete-timeout: 30000
      config:
        server-addr: 117.50.197.170:8848
        username: nacos
        password: olN2y)]VzEISLITO#_}L0J^$>Nk)1S~W
        namespace: ba1493dc-20fa-413b-84e1-d929c9a4aeac
        group: DEFAULT_GROUP
        file-extension: yaml
        # 配置刷新
        refresh-enabled: true

