# 核心发布者服务 - 开发环境主配置文件
# 注意：业务配置和敏感信息已移至Nacos配置中心

# 服务器配置
server:
  port: 8084

# Spring基础配置
spring:
  # 应用名称
  application:
    name: core-publisher
  
  # 配置导入 - 从Nacos加载配置
  config:
    import: nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
  
  # 数据源配置
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:banyu_mall}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # Redis配置
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2
          max-wait: -1ms
  
  # Nacos服务注册与发现配置
  cloud:
    nacos:
      # 服务发现配置
      discovery:
        server-addr: 117.50.197.170:8848
        username: nacos
        password: olN2y)]VzEISLITO#_}L0J^$>Nk)1S~W
        namespace: ba1493dc-20fa-413b-84e1-d929c9a4aeac
        group: DEFAULT_GROUP
        # 注册配置
        register-enabled: true
        # 心跳间隔
        heart-beat-interval: 5000
        # 心跳超时时间
        heart-beat-timeout: 15000
        # 实例删除超时时间
        ip-delete-timeout: 30000
      
      # 配置中心配置
      config:
        server-addr: 117.50.197.170:8848
        username: nacos
        password: olN2y)]VzEISLITO#_}L0J^$>Nk)1S~W
        namespace: ba1493dc-20fa-413b-84e1-d929c9a4aeac
        group: DEFAULT_GROUP
        file-extension: yaml
        # 配置刷新
        refresh-enabled: true
        # 配置超时时间
        timeout: 3000
        # 配置重试次数
        retry-time: 2000
        # 长轮询超时时间
        long-poll-timeout: 46000

  # 启动性能优化（开发环境）
  main:
    lazy-initialization: true  # 开发环境启用懒加载
    # 排除不需要的自动配置
    banner-mode: off  # 关闭启动横幅
    # 允许循环依赖（开发环境）
    allow-circular-references: true
    # 允许Bean定义覆盖
    allow-bean-definition-overriding: true
  # JMX配置
  jmx:
    enabled: false  # 开发环境关闭JMX
  # 自动配置排除
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration
      - org.springframework.boot.autoconfigure.websocket.servlet.WebSocketServletAutoConfiguration

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    # 开发环境可以开启SQL日志，生产环境建议关闭
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/*.xml

# Knife4j配置
knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表
    enable-version: false
    enable-reload-cache-parameter: false
    enable-after-script: true
    enable-filter-multipart-api-method-type: POST
    enable-filter-multipart-apis: false
    enable-request-cache: true
    enable-host: false
    enable-host-text: ""
    enable-home-custom: false
    home-custom-path: ""
    enable-search: true
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: Apache License 2.0 | Copyright  2024-[banyuMall](https://github.com/scccy/banyuMall)
    enable-dynamic-parameter: false
    enable-debug: true
    enable-open-api: false
    enable-group: true

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  # 应用信息配置
  info:
    env:
      enabled: true
    git:
      mode: full

# 日志配置（开发环境优化日志）
logging:
  config: classpath:log4j2.xml
  level:
    com.origin.publisher: info
    org.springframework.web: warn
    com.origin.publisher.service: info
    # 禁用Log4j2包扫描警告
    org.apache.logging.log4j.status: ERROR
    org.apache.logging.log4j.core.config: ERROR
    # 减少Spring Boot启动日志
    org.springframework.boot.autoconfigure: warn
    org.springframework.context.annotation: warn
    # 减少Bean扫描日志
    org.springframework.context.annotation.ClassPathBeanDefinitionScanner: warn
    # 减少自动配置日志
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger: warn
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/core-publisher.log 