# 核心发布者服务 - 开发环境主配置文件
# 注意：业务配置和敏感信息已移至Nacos配置中心

# 服务器配置
server:
  port: 8084

# Spring基础配置
spring:
  # 应用名称
  application:
    name: core-publisher
  
  # 配置导入 - 从Nacos加载配置
  config:
    import: nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
  
  # Nacos服务注册与发现配置
  cloud:
    nacos:
      # 服务发现配置
      discovery:
        server-addr: 117.50.197.170:8848
        username: nacos
        password: olN2y)]VzEISLITO#_}L0J^$>Nk)1S~W
        namespace: ba1493dc-20fa-413b-84e1-d929c9a4aeac
        group: DEFAULT_GROUP
        # 注册配置
        register-enabled: true
        # 心跳间隔
        heart-beat-interval: 5000
        # 心跳超时时间
        heart-beat-timeout: 15000
        # 实例删除超时时间
        ip-delete-timeout: 30000
      
      # 配置中心配置
      config:
        server-addr: 117.50.197.170:8848
        username: nacos
        password: olN2y)]VzEISLITO#_}L0J^$>Nk)1S~W
        namespace: ba1493dc-20fa-413b-84e1-d929c9a4aeac
        group: DEFAULT_GROUP
        file-extension: yaml
        # 配置刷新
        refresh-enabled: true
        # 配置超时时间
        timeout: 3000
        # 配置重试次数
        retry-time: 2000
        # 长轮询超时时间
        long-poll-timeout: 46000

  # 启动性能优化（开发环境）
  main:
    lazy-initialization: true  # 开发环境启用懒加载
  # JMX配置
  jmx:
    enabled: false  # 开发环境关闭JMX

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  # 应用信息配置
  info:
    env:
      enabled: true
    git:
      mode: full

# 日志配置（开发环境详细日志）
logging:
  config: classpath:log4j2.xml
  level:
    com.origin.publisher: debug
    org.springframework.web: debug
    com.origin.publisher.service: debug
    # 禁用Log4j2包扫描警告
    org.apache.logging.log4j.status: ERROR
    org.apache.logging.log4j.core.config: ERROR
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/core-publisher.log 